name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
    
    - name: Publish      
      run: |
        mkdir build
        GOOS=linux GOARCH=amd64 go build -o build/Unlocker-linux-x64
        GOOS=linux GOARCH=386 go build -o build/Unlocker-linux-x86
        GOOS=windows GOARCH=amd64 go build -o build/Unlocker-windows-x64.exe
        GOOS=windows GOARCH=386 go build -o build/Unlocker-windows-x86.exe

    - name: Test
      run: go test -v .
    - uses: actions/upload-artifact@v2
      with:
        name: Release
        path: build
